spring:
  profiles:
    active: dev

  datasource:
    urlBase: jdbc:mysql://vizicard.ru:3306/
    username: vizicard
    password: sdvsdDFVDFdfvdfvDSV
    driver-class-name: com.mysql.cj.jdbc.Driver
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        id:
          new_generator_mappings: false
  mail:
    host: smtp.yandex.ru
    port: 587
    username: info@vizicard.ru
    password: dfbdfHBgvgv89iudfhbiu
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
#server:
#  error:
#    include-message: always
#  servlet:
#    context-path: /api
security:
  jwt:
    token:
      secret-key: hJKnai8ah2

#UserController:
#  signin: Authenticates user and returns its JWT token.
#  signup: Creates user and returns its JWT token
#  delete: Deletes specific user by username
#  search: Returns specific user by username
#  me: Returns current user's data
#  update: Updates most user's fields
