spring:
  datasource:
    url: jdbc:mysql://vizicard.ru:3306/dev
    username: vizicard
    password: sdvsdDFVDFdfvdfvDSV

    driver-class-name: com.mysql.cj.jdbc.Driver
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        id:
          new_generator_mappings: false
  mail:
    host: vizicard.ru
    port: 587
    username: info@vizicard.ru
    password: dgdfgDFgdfbgd
    properties:
      starttls.enable: true

server:
   port: 8080 # This is the default port anyway, but you can change it here

security:
  jwt:
    token:
      secret-key: secret-key
#      expire-length: 300000 # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds

#  spring.mail.properties.mail.smtp.auth=true

#UserController:
#  signin: Authenticates user and returns its JWT token.
#  signup: Creates user and returns its JWT token
#  delete: Deletes specific user by username
#  search: Returns specific user by username
#  me: Returns current user's data
#  update: Updates most user's fields
